import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/authProvider";
import TanstackProviders from "./TanstackProvider/TanstackProvider";
import DashBoardDataProvider from "./Component/UserComponent/UserDashBoardDataContext/DashBoardDataProvider";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "./context/UserContext";
import ChallangesDataProvider from "./Component/ChallangesProgramComponent/ChellangesContexts/ChallangesDataProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "CareHive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <UserProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
          >
            <TanstackProviders>
              <AuthProvider>
                <DashBoardDataProvider>
                  <ChallangesDataProvider>
                    {children}
                  </ChallangesDataProvider>
                </DashBoardDataProvider>
              </AuthProvider>
            </TanstackProviders>
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
