export const weekDays = [
    { name: "Sunday", value: 'sunday' },
    { name: "Monday", value: 'monday' },
    { name: "Tuesday", value: 'tuesday' },
    { name: "Wednesday", value: 'wednesday' },
    { name: "Thursday", value: 'thursday' },
    { name: "Friday", value: 'friday' },
    { name: "Saturday", value: 'saturday' },
];

export const languages = [
    { name: "Bengali", value: 'bengali' },
    { name: "Hindi", value: 'hindi' },
    { name: "English", value: 'english' },
];


export const bangladeshDistricts = [
  { name: "Bagerhat", value: "bagerhat" },
  { name: "Bandarban", value: "bandarban" },
  { name: "Barguna", value: "barguna" },
  { name: "Barishal", value: "barishal" },
  { name: "Bhola", value: "bhola" },
  { name: "Bogura", value: "bogura" },
  { name: "Brahmanbaria", value: "brahmanbaria" },
  { name: "Chandpur", value: "chandpur" },
  { name: "Chapainawabganj", value: "chapainawabganj" },
  { name: "Chattogram", value: "chattogram" },
  { name: "Chuadanga", value: "chuadanga" },
  { name: "Cox’s Bazar", value: "coxs_bazar" },
  { name: "Cumilla", value: "cumilla" },
  { name: "Dhaka", value: "dhaka" },
  { name: "Dinajpur", value: "dinajpur" },
  { name: "Faridpur", value: "faridpur" },
  { name: "Feni", value: "feni" },
  { name: "Gaibandha", value: "gaibandha" },
  { name: "Gazipur", value: "gazipur" },
  { name: "Gopalganj", value: "gopalganj" },
  { name: "Habiganj", value: "habiganj" },
  { name: "Jamalpur", value: "jamalpur" },
  { name: "Jashore", value: "jashore" },
  { name: "Jhalokati", value: "jhalokati" },
  { name: "Jhenaidah", value: "jhenaidah" },
  { name: "Joypurhat", value: "joypurhat" },
  { name: "Khagrachhari", value: "khagrachhari" },
  { name: "Khulna", value: "khulna" },
  { name: "Kishoreganj", value: "kishoreganj" },
  { name: "Kurigram", value: "kurigram" },
  { name: "Kushtia", value: "kushtia" },
  { name: "Lakshmipur", value: "lakshmipur" },
  { name: "Lalmonirhat", value: "lalmonirhat" },
  { name: "Madaripur", value: "madaripur" },
  { name: "Magura", value: "magura" },
  { name: "Manikganj", value: "manikganj" },
  { name: "Meherpur", value: "meherpur" },
  { name: "Moulvibazar", value: "moulvibazar" },
  { name: "Munshiganj", value: "munshiganj" },
  { name: "Mymensingh", value: "mymensingh" },
  { name: "Naogaon", value: "naogaon" },
  { name: "Narail", value: "narail" },
  { name: "Narayanganj", value: "narayanganj" },
  { name: "Narsingdi", value: "narsingdi" },
  { name: "Natore", value: "natore" },
  { name: "Nawabganj", value: "nawabganj" },
  { name: "Netrakona", value: "netrakona" },
  { name: "Nilphamari", value: "nilphamari" },
  { name: "Noakhali", value: "noakhali" },
  { name: "Pabna", value: "pabna" },
  { name: "Panchagarh", value: "panchagarh" },
  { name: "Patuakhali", value: "patuakhali" },
  { name: "Pirojpur", value: "pirojpur" },
  { name: "Rajbari", value: "rajbari" },
  { name: "Rajshahi", value: "rajshahi" },
  { name: "Rangamati", value: "rangamati" },
  { name: "Rangpur", value: "rangpur" },
  { name: "Satkhira", value: "satkhira" },
  { name: "Shariatpur", value: "shariatpur" },
  { name: "Sherpur", value: "sherpur" },
  { name: "Sirajganj", value: "sirajganj" },
  { name: "Sunamganj", value: "sunamganj" },
  { name: "Sylhet", value: "sylhet" },
  { name: "Tangail", value: "tangail" },
  { name: "Thakurgaon", value: "thakurgaon" }
];
